parameters:
  scenario: nic
  sub_dir: densenet/125/nic
  cls: dense_freeze_till3
  method: task_mem
  n_classes: 50
  #Augmentation
  aug: True
  aug_type: center_224
  #replay
  replay_examples: 250
  replay_used: 750
  replay_epochs: 2
  #review
  review_lr_factor: 1
  review_size: 20000
  review_epoch: 1
  #train
  batch_size: 32
  epochs: 1
  optimizer: SGD
  nesterov: True
  momentum: 0
  weight_decay: 0.001
  lr: 0.01
  #misc
  verbose: False
  preload_data: False
  use_cuda: True
